//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leagues.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LeaguesEntities : DbContext
    {
        public LeaguesEntities()
            : base("name=LeaguesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<TuesdayMatch> TuesdayMatches { get; set; }
        public virtual DbSet<TuesdaySchedule> TuesdaySchedules { get; set; }
        public virtual DbSet<TuesdayTeam> TuesdayTeams { get; set; }
        public virtual DbSet<WednesdayMatch> WednesdayMatches { get; set; }
        public virtual DbSet<WednesdaySchedule> WednesdaySchedules { get; set; }
        public virtual DbSet<WednesdayTeam> WednesdayTeams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<Tuesday_GetMatchAll_Result> Tuesday_GetMatchAll(Nullable<int> weekid)
        {
            var weekidParameter = weekid.HasValue ?
                new ObjectParameter("weekid", weekid) :
                new ObjectParameter("weekid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tuesday_GetMatchAll_Result>("Tuesday_GetMatchAll", weekidParameter);
        }
    
        public virtual ObjectResult<Wednesday_GetMatchAll_Result> Wednesday_GetMatchAll(Nullable<int> weekid)
        {
            var weekidParameter = weekid.HasValue ?
                new ObjectParameter("weekid", weekid) :
                new ObjectParameter("weekid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Wednesday_GetMatchAll_Result>("Wednesday_GetMatchAll", weekidParameter);
        }
    }
}
