//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leagues.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuesdayTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuesdayTeam()
        {
            this.TuesdayMatches = new HashSet<TuesdayMatch>();
            this.TuesdayMatches1 = new HashSet<TuesdayMatch>();
        }
    
        public int id { get; set; }
        public int Skip { get; set; }
        public Nullable<int> Lead { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuesdayMatch> TuesdayMatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuesdayMatch> TuesdayMatches1 { get; set; }
    }
}
