//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leagues.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WednesdayMatchView
    {
        public int id { get; set; }
        public string Date { get; set; }
        public int Rink { get; set; }
        public Nullable<int> Team1 { get; set; }
        public Nullable<int> Team2 { get; set; }
        public string Skip1 { get; set; }
        public string ViceSkip1 { get; set; }
        public string Lead1 { get; set; }
        public string Skip2 { get; set; }
        public string ViceSkip2 { get; set; }
        public string Lead2 { get; set; }
    }
}
