//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leagues.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WednesdayMatch
    {
        public int id { get; set; }
        public int GameDate { get; set; }
        public int Rink { get; set; }
        public int Team1 { get; set; }
        public Nullable<int> Team2 { get; set; }
        public int Team1Score { get; set; }
        public int Team2Score { get; set; }
        public int Forfeit { get; set; }
    
        public virtual WednesdaySchedule WednesdaySchedule { get; set; }
        public virtual WednesdayTeam WednesdayTeam { get; set; }
        public virtual WednesdayTeam WednesdayTeam1 { get; set; }
    }
}
