//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leagues.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WednesdaySchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WednesdaySchedule()
        {
            this.WednesdayMatches = new HashSet<WednesdayMatch>();
        }
    
        public int id { get; set; }
        public System.DateTime GameDate { get; set; }
        public string GameDateFormatted { get; set; }
        public bool IsCancelled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WednesdayMatch> WednesdayMatches { get; set; }
    }
}
